### ISSUE TITLE
Heroku Server Error

### ISSUE THREAD

**Issue by prashantplusplus** [FractalMarchers/fm3#5]
`index.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

So I have deployed the main git on Heroku https://fractal-marchers.herokuapp.com/ . As Heroku looks for server file I added server.js and in package.json mentioned the script to run server js which serve index.html

But I am getting the above error. Any idea to fix the above?

**Comment by RMichaelSwan** [comment]
Not sure. Maybe related to how I'm importing the js files. In general I'm not sure why you're using Heroku though, we're already getting it automatically hosted to https://fractalmarchers.github.io/fm3/ whenever you push to main (usually takes a few minutes to update)

**Comment by prashantplusplus** [comment]
I know, its just that I am now fond of using heroku cli :p

**Comment by RMichaelSwan** [comment]
> I know, its just that I am now fond of using heroku cli :p

Heh, well good luck then 😛 . I've only used heroku once.
