### ISSUE TITLE
Lighting discontinuity

### ISSUE THREAD

**Issue by RMichaelSwan** [FractalMarchers/fm3#9]
Not sure if intentional, but objects that cross a Y of 0.0 tend to have a discontinuity in the lighting (a line that is just black).

**Comment by mozhdehrouhsedaghat** [comment]
I am not sure if you mean this but as I have a plane at y =-1 in my scene, points at this location are colored dark (different from the rest of the scene). To avoid it simply remove the if-else statement in the lighting function and only keep the statement inside the "else" condition in the main body of the lighting function.
